pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    yarn --pure-lockfile
    yarn test
    yarn lint
    yarn format:prettier && git diff --exit-code || exit 1
  displayName: 'yarn install and build'
